# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Francisco Santana-Pardo
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Landing page for my domain.
  I am a software developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://franciscosp.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: &twitter pacismo
github_username: &github pacismo
google_analytics: &ua-analytics UA-184595877-2
# GA4_analytics: G-6WXCCETQ9V

locale: "en-US"

# Build settings
# Remote themes on GitHub Pages must be configured with this tag:
remote_theme: "mmistakes/minimal-mistakes" # see: https://mmistakes.github.io/minimal-mistakes/docs/
minimal_mistakes_skin: "mint"

title_separator: "|"
subtitle: "General Blog"
name: "Francisco Santana-Pardo"
repository: "pacismo/pacismo.github.io"
search: true
breadcrumbs: false

collections:
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title/
  archives:
    output: true
    permalink: /:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: true
      author_profile: true
      author: Francisco Santana
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      show_date: false
      read_time: false
      author_profile: false
      comments: false
      share: false
  # _archives
  - scope:
      path: ""
      type: archives
    values:
        layout: single
        show_date: false
        read_time: false
        author_profile: false
        comments: false
        share: false

category_archive:
  type: liquid
  path: /posts-by-category/
tag_archive:
  type: liquid
  path: /posts-by-tag/

twitter:
  username: *twitter
social:
  type: Person
  name: "Francisco Santana-Pardo"
  links:
    - "https://twitter.com/pacismo"
    - "https://instagram.com/pacismo"
    - "https://github.com/pacismo"
    - "https://twitch.tv/pacismo"
analytics:
  provider: "google-universal"
  google:
    tracking_id: *ua-analytics
    anonymize_ip: false

footer:
  links:
    - label: "License"
      url: "/license/"
      icon: "fab fas fa-certificate"

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Add the following folders to the website.
include: ["_pages", "_archives", "_icons"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - New-Post.ps1
  - Start-Test.ps1
  - Remove-Cache.ps1
  - README.md
  - github-pages.code-workspace
  - CNAME
  - Gemfile
  - Gemfile.lock
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
