baseURL = 'https://franciscosp.com/'
languageCode = 'en-us'
title = 'Francisco Santana'
theme = "franciscosp-theme"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 30

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 31

[[params.socials]]
name = "LinkedIn"
link = "https://www.linkedin.com/in/fsantanapardo"

[params]
math = true
fa_code = "ffc224c250"

[params.home]
pageCount = 5
paginate = ["posts"]
resume = false
spotlight.characterLimit = 2000

[permalinks]
[permalinks.page]
posts = "/posts/:year/:month/:slug/"

[pagination]
disableAliases = false
pagerSize = 10
path = 'page'
