baseURL = 'https://franciscosp.com/'
languageCode = 'en-us'
title = 'Francisco Santana'
theme = "franciscosp-theme"

[params]
math = true

[params.home]
pageCount = 5
paginate = ["posts"]
resume = false
spotlight.characterLimit = 2000

[permalinks]
[permalinks.page]
posts = "/posts/:year/:month/:slug/"
