[[education]]
institution = "University of Massachusetts, Amherst"
area = "Computer Science"
startDate = "2021-09-01"
endDate = "2024-05-17"
score = "3.7 GPA"
studyType = "Bachelor's of Science"
url = "https://umass.edu"
image = "resume/umass-seal.png"
